### PR TITLE
Selectively hide header text

### LINKED ISSUE #68: Hide header text on small screen resolutions
The header text causes the login and register buttons to bleed off the page on mobile screens.

### PR DESCRIPTION
**Pull request by ghost**
Use a media query to hide the header text on small screen resolutions so the header buttons don't bleed off-page on mobile resolutions

Resolves #68

### CODE REVIEW

**Comment by amgoodfellow** [comment]
I really like this fix, but do you think we could get it so that the buttons stick to the right in a mobile view?

image

**Comment by ghost** [comment]
Okay, they should stay aligned right now. Though if someone makes the screen suuper tiny they do bunch up, but I don't think there is any such mobile screen that is actually that small.
image

Anyway, I would think we would probably want to solve that issue by setting a min width on our application root.

**Comment by ghost** [comment]
On a simulated Galaxy:
image

**Review by amgoodfellow — APPROVED** [review]
Looks good! Thanks @OUnagiles

**Pull request merged**
